services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    command: serve

  pgvector:
    image: 'ankane/pgvector:latest'
    environment:
      - 'POSTGRES_DB=vectordb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    command: >
      postgres -c 'shared_preload_libraries=vector,pg_stat_statements'

volumes:
  ollama_data:
  pgvector_data:
